### ISSUE TITLE
Doesn't work on Marshmallow

### ISSUE THREAD

**Issue by kusiak** [shantanugoel/ExchangeBypassXposed#4]
The fix does not work on my stock, rooted, xposed Nexus 6P. Any hope of a fix for the most recent android version? 😄

**Comment by shantanugoel** [comment]
I haven't upgraded it for M as I don't use exchange anymore on my phone. PR is welcome if anyone wants to update it.

**Comment by kusiak** [comment]
Ok, if I find out how xposed modules work I'll look at the problem, thanks for writing the module anyways 👍
